name: kazi_companies
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  go_router: ^14.1.4
  kazi_core: 
    git:
      url: https://github.com/lucas-242/kazi_core.git
      ref: master
  kazi_design_system: 
    git:
      url: https://github.com/lucas-242/kazi_design_system.git
      ref: 0.1.1
    # path: C:/Projetos/kazi_design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true